---
name: push
on: push
name: 'Cloud native buildpacks build'

jobs:
  buildpacks:
    name: 'Run Buildpacks'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Check out source code'
        uses: actions/checkout@v3

      - name: 'Set up Buildpacks'
        uses: buildpacks/github-actions/setup-pack@v5.0.0

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Package the application with Buildpacks and publish to container registry'
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          pack build ${{ env.full-image-name }} \
            --builder paketobuildpacks/builder:base \
            --env BP_CPYTHON_VERSION='3.11.*'
            --publish

      - name: 'Cleanup runner work directory'
        if: ${{ always() }}
        run: |
          rm -rf ./*
          rm -rf ./.??*
